Remove all tabs from bash scripts

diff --git a/src/main/resources/com/typesafe/sbt/packager/linux/control-functions b/src/main/resources/com/typesafe/sbt/packager/linux/control-functions
--- a/src/main/resources/com/typesafe/sbt/packager/linux/control-functions
+++ b/src/main/resources/com/typesafe/sbt/packager/linux/control-functions
@@ -11,22 +11,22 @@
 addUser() {
     user="$1"
     if [ -z "$user" ]; then
-	echo "usage: addUser user [group] [description] [shell]"
-	exit 1
+        echo "usage: addUser user [group] [description] [shell]"
+        exit 1
     fi
     uid="$2"
     if [ -z "$uid" ]; then
-	uid_flags=""
-	  else
-  uid_flags="--uid $uid"
+        uid_flags=""
+    else
+        uid_flags="--uid $uid"
     fi
     group=${3:-$user}
     descr=${4:-No description}
     shell=${5:-/bin/false}
     if ! getent passwd | grep -q "^$user:";
     then
-	echo "Creating system user: $user in $group with $descr and shell $shell"
-	useradd $uid_flags --gid $group -r --shell $shell -c "$descr" $user
+        echo "Creating system user: $user in $group with $descr and shell $shell"
+        useradd $uid_flags --gid $group -r --shell $shell -c "$descr" $user
     fi
 }
 
@@ -37,14 +37,14 @@ addGroup() {
     group="$1"
     gid="$2"
     if [ -z "$gid" ]; then
-	  gid_flags=""
-  else
-    gid_flags="--gid $gid"
-  fi
+        gid_flags=""
+    else
+        gid_flags="--gid $gid"
+    fi
     if ! getent group | grep -q "^$group:" ;
     then
-	echo "Creating system group: $group"
-	groupadd $gid_flags -r $group
+        echo "Creating system group: $group"
+        groupadd $gid_flags -r $group
     fi
 }
 
@@ -52,11 +52,11 @@ addGroup() {
 # $1 = user
 deleteUser() {
     if hash deluser 2>/dev/null; then
-	deluser --quiet --system $1 > /dev/null || true
+        deluser --quiet --system $1 > /dev/null || true
     elif hash userdel 2>/dev/null; then
-	userdel $1
+        userdel $1
     else
-	echo "WARNING: Could not delete user $1 . No suitable program (deluser, userdel) found"
+        echo "WARNING: Could not delete user $1 . No suitable program (deluser, userdel) found"
     fi
 }
 
@@ -64,11 +64,11 @@ deleteUser() {
 # $1 = group
 deleteGroup() {
     if hash delgroup 2>/dev/null; then
-	delgroup --quiet --system $1 > /dev/null || true
+        delgroup --quiet --system $1 > /dev/null || true
     elif hash groupdel 2>/dev/null; then
-	groupdel $1
+        groupdel $1
     else
-	echo "WARNING: Could not delete user $1 . No suitable program (delgroup, groupdel) found"
+        echo "WARNING: Could not delete user $1 . No suitable program (delgroup, groupdel) found"
     fi
 }
 
