Add new system loader setting for file descriptor limit (#954)
* Added 'fileDescriptorLimit' systemloader key, with support for Upstart (default 1024).

* Added support for fileDescriptorLimit to systemd and systemv loaders. Default for all loaders is 1024.

* Moved fileDescriptorLimit key and script replacements to linux plugin.

* Cleanup.

diff --git a/src/main/resources/com/typesafe/sbt/packager/archetypes/systemloader/systemv/start-rpm-template b/src/main/resources/com/typesafe/sbt/packager/archetypes/systemloader/systemv/start-rpm-template
--- a/src/main/resources/com/typesafe/sbt/packager/archetypes/systemloader/systemv/start-rpm-template
+++ b/src/main/resources/com/typesafe/sbt/packager/archetypes/systemloader/systemv/start-rpm-template
@@ -72,6 +72,11 @@ fi
 
 start() {
     [ -x $exec ] || exit 5
+    # Set the file descriptor limit
+    ulimit -n ${{file_descriptor_limit}} ${{file_descriptor_limit}}
+    if [ $? -ne 0 ]; then
+        echo -n $"Failed to set file descriptor limit: ${{file_descriptor_limit}}"
+    fi
     echo -n $"Starting $prog: "
     daemon --check $prog --user $DAEMON_USER --pidfile $PIDFILE "$RUN_CMD"
     retval=$?
