Test for multiple mains and forwarder scripts for AshStartScriptTemplate

diff --git a/src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-forwarder-template b/src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-forwarder-template
--- a/src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-forwarder-template
+++ b/src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-forwarder-template
@@ -1,11 +1,8 @@
 #!/bin/sh
 
 
-export APP_NAME
-export APP_HOME
 export START_SCRIPT
 export QUALIFIED_CLASS_NAME
-export ARGS
 export DEBUG="false"
 
 
@@ -23,13 +20,13 @@ die() {
 }
 
 resolve_primary_environment_variables() {
-  readonly APP_NAME="${0##*/}" || die "Error resolving APP_NAME" $?
-  readonly APP_HOME="$(dirname "$(realpath "$0")")" || die "Error resolving APP_HOME" $?
-  readonly START_SCRIPT="$APP_HOME/${{startScript}}" || die "Error resolving START_SCRIPT" $?
-  readonly QUALIFIED_CLASS_NAME=${{qualifiedClassName}} || die "Error resolving QUALIFIED_CLASS_NAME" $?
+  readonly START_SCRIPT="$(dirname $(realpath $0))/${{startScript}}" || die "Error resolving START_SCRIPT" $?
+  readonly QUALIFIED_CLASS_NAME="${{qualifiedClassName}}" || die "Error resolving QUALIFIED_CLASS_NAME" $?
 }
 
 main() {
   resolve_primary_environment_variables || die "Error resolving primary environment variables" $?
   exec "$START_SCRIPT" -main "$QUALIFIED_CLASS_NAME" "$@"
 }
+
+main "$@"
